Fase3/Fase3/Controllers/EntradaController.cs
using Logica;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fase3.Controllers
{
    public class EntradaController : Controller
    {
        ProveedorLogic proveedor = new ProveedorLogic();
        EntradaBodegaLogic entrada = new EntradaBodegaLogic();
        UsuarioOperativoLogic usuario = new UsuarioOperativoLogic();
        ProductoLogic producto = new ProductoLogic();
        DetalleEntradaLogic detalle = new DetalleEntradaLogic();
        NivelLogic nivel = new NivelLogic();
        AsignarNivelLogic asignar = new AsignarNivelLogic();

        public ActionResult Entrada()
        {
            return View(proveedor.listaProveedores(int.Parse(Session["Usuario"].ToString())));
        }


        public ActionResult registrarEntrada(int codigoEntrada, string proveedor, string fecha)
        {
            Session["idEntrada"] = codigoEntrada;
            if (entrada.agregarEntrada(codigoEntrada, fecha, proveedor, usuario.buscarUsuario(Session["usuarioOperativo"].ToString()).cui, int.Parse(Session["usuario"].ToString())))
            {
                return Content("<script> alert('Entrada Registrada');" +
                    "window.location.href='DetalleEntrada' </script>");
            }
            else
            {
                return Content("<script> alert('No se pudo registrar la Entrada');" +
                    "window.location.href='Entrada' </script>");
            }
        }

        public ActionResult DetalleEntrada()
        {
            return View(producto.listaProductos(int.Parse(Session["usuario"].ToString())));
        }

        public ActionResult registrarDetalle(double precio, int tipoCosteo, int cantidad, int? logica, string producto)
        {
            if (detalle.addDetalleEntrada(precio, cantidad, producto, int.Parse(Session["idEntrada"].ToString()), tipoCosteo, logica, int.Parse(Session["usuario"].ToString())))
            {
                return Content("<script> alert('Detalle Registrado'); " +
                    "window.location.href='DetalleEntrada' </script>");
            }
            else
            {
                return Content("<script> alert('No se pudo registrar el detalle'); " +
                    "window.location.href='DetalleEntrada' </script>");
            }
        }


        public ActionResult asignarNivel()
        {
            ViewBag.niveles = nivel.idNiveles(int.Parse(Session["usuario"].ToString()));
            return View(detalle.listaDetalles(int.Parse(Session["idEntrada"].ToString())));
        }

        public ActionResult Asignar(int cantidad, int idDetalle, int idNivel)
        {
            if (asignar.asignarNivel(cantidad, idNivel, idDetalle))
            {
                return Content("<script> alert('Asignado');" +
                "window.location.href='asignarNivel' </script>");
            }
            else
            {
                return Content("<script> alert('No se pudo asignar');" +
                "window.location.href='asignarNivel' </script>");
            }
        }

        // GET: Entrada
        public ActionResult Index()
        {
            return View();
        }


        
    }
}

Fase3/Fase3/Views/Entrada/DetalleEntrada.cshtml
@model LinkedList<Entidad.Producto>

@{
    ViewBag.Title = "DetalleEntrada";
    Layout = "~/Views/Layauts/BarraNavegacion.cshtml";
}

<h2>DetalleEntrada</h2>

<div class="row">
    <div class="col m12">
        <div class="card">
            <div class="card-content">
                <span class="card-title"> Detalle de la Entrega</span>
                @using (Html.BeginForm("registrarDetalle", "Entrada", FormMethod.Post))
                {
                    <form>
                        <div class="row">
                            <div class="col m4">
                                Precio:
                                <input type="number" step="0.01" required placeholder="Precio" name="precio" />
                                Tipo de Costeo:
                                <select required name="tipoCosteo">
                                    <option selected disabled> Elije tu Opción</option>
                                    <option value="1"> Saldo</option>
                                    <option value="2"> Lote </option>
                                </select>
                            </div>
                            <div class="col m4">
                                Cantidad:
                                <input type="number" step="1" required placeholder="Cantidad" name="cantidad" />
                                Tipo de Lógica:
                                <select name="logica">
                                    <option selected disabled value="0"> Elija su Opción</option>
                                    <option value="1"> UEPS</option>
                                    <option value="2">PEPS</option>
                                </select>
                            </div>
                            <div class="col m4">
                                Producto:
                                <select required name="producto">
                                    <option selected readonly="true"> Elije tu Opción </option>
                                    @foreach (var item in Model)
                                    {
                                        <option> @item.codigoProducto, @item.nombreProducto </option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col m12 center">
                                <button class="btn green"> Agregar <i class="material-icons right"> add_circle</i> </button>
                                <a class="btn blue" href="asignarNivel"> Asignar Productos a Bodegas <i class="material-icons right">assignment</i> </a>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

Fase3/Fase3/Views/Entrada/Entrada.cshtml
@model LinkedList<Entidad.Proveedor>
@{
    ViewBag.Title = "Entrada";
    Layout = "~/Views/Layauts/BarraNavegacion.cshtml";
}

<h2>Entrada</h2>


<div class="row">
    <div class="col m12">
        <div class="card z-depth-3">
            <div class="card-content">
                <span class="card-title"> Registrar Entrada </span>
                @using (Html.BeginForm("registrarEntrada", "Entrada", FormMethod.Post))
                {
                    <form>
                        <div class="row">
                            <div class="col m6">
                                Código Entrada:
                                <input type="number" name="codigoEntrada" step="0.01" placeholder="Código Entrada" required />
                                Proveedor:
                                <select name="proveedor" required>
                                    <option selected disabled>Elija Su Opción</option>
                                    @foreach (var item in Model)
                                    {
                                        <option> @item.nit, @item.nombre </option>
                                    }
                                </select>
                            </div>
                            <div class="col m6">
                                Fecha Entrada:
                                <input type="date" name="fecha" required />
                                <button class="btn green">
                                    Registrar Entrada
                                    <i class="material-icons right"> add_circle </i>
                                </button>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

Fase3/Fase3/Views/Entrada/asignarNivel.cshtml
@model LinkedList<Entidad.DetalleEntrada>

@{
    ViewBag.Title = "asignarNivel";
    Layout = "~/Views/Layauts/BarraNavegacion.cshtml";
}
<h2>asignarNivel</h2>

<table>
    <tr>
        <th> Id </th>
        <th> Producto </th>
        <th> Precio </th>
        <th> Cantidad </th>
        <th> Costeo </th>
        <th> Acciones </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td> @item.idDetalleEntrada </td>
            <td> @item.producto </td>
            <td> @(String.Format("{0:c}", item.precio)) </td>
            <td> @item.cantidad </td>
            <td> @item.costeo </td>
            <td>
                <a class="modal-trigger" id="btnAsignar" title="Asignar Nivel"
                   href="#modal1"
                   data-idDetalle="@item.idDetalleEntrada"> <i class="material-icons blue-text">storage</i> </a>
            </td>
        </tr>
    }
</table>

<!-- Modal Structure -->
<div id="modal1" class="modal">
    <div class="modal-content">
        <div class="container center">
            <h3>Asignar Nivel</h3>
        </div>
        <div>
            <div class="row">
                <div>
                    @using (Html.BeginForm("Asignar", "Entrada", FormMethod.Post))
                    {
                        <form id="modificar">
                            <div class="col s6">
                                Niveles:
                                <select name="idNivel">
                                    <option selected disabled> Escoja su Opción </option>
                                    @foreach (var item2 in ViewBag.niveles)
                                    {
                                        <option> @item2.idNivel </option>
                                    }
                                </select>
                                Cantidad:
                                <input name="cantidad" type="text" placeholder="Cantidad" />
                            </div>
                            <div class="col s6">
                                Id Detalle:
                                <input type="text" id="Detalle" name="idDetalle" readonly/>
                            </div>
                            <div class="center">
                                <button class="btn"> Asignar </button>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>

    @*<div class="modal-content">
            <h4>Modal Header</h4>
            <p>A bunch of text</p>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
        </div>*@
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.modal');
        var instances = M.Modal.init(elems);
    });

    $(document).on('click', "#btnAsignar", function () {
        let { iddetalle } = $(this).data();
        console.log($(this).data());
        console.log(iddetalle);
        $(".modal-content #Detalle").val(iddetalle);
    });

</script>